# Generated by Django 5.1.2 on 2024-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=models.CharField(choices=[('job_poster', 'Job Poster'), ('job_seeker', 'Job Seeker')], max_length=10),
        ),
    ]
