# Generated by Django 5.1.2 on 2024-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0002_developer_email_alter_developer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='github_url',
            field=models.URLField(null=True),
        ),
    ]
