# Generated by Django 5.1.2 on 2024-11-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0003_alter_developer_birth_date_alter_developer_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
