# Generated by Django 5.1.2 on 2024-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
