# Generated by Django 5.1.2 on 2024-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0009_jobpost_views_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='devsearchey.profile'),
        ),
    ]
