# Generated by Django 5.1.2 on 2024-11-05 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0010_jobpost_bookmark_count_jobpost_bookmarked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by_profiles', to='devsearchey.jobpost'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_job_posts', to='devsearchey.profile'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
