# Generated by Django 5.1.2 on 2024-11-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0011_profile_bookmarked_posts_alter_jobpost_bookmarked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='reference_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
