# Generated by Django 5.1.2 on 2024-11-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0022_remove_jobpost_bookmarked_by_alter_forumpost_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'permissions': [('delete_explicit_forumpost', 'Can delete forum posts containing explicit language')]},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'permissions': [('delete_explicit_jobpost', 'Can delete job posts containing explicit language')]},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('delete_bad_bio', 'Can delete user bios containing bad language')]},
        ),
    ]
