# Generated by Django 5.1.2 on 2024-11-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsearchey', '0023_alter_forumpost_options_alter_jobpost_options_and_more'),
        ('devsearchey', '0024_create_moderators_group'),
    ]

    operations = [
    ]
